### ISSUE TITLE
tools are not loaded after demo_scripts

### ISSUE THREAD

**Issue by ilya112358** [qualisys/qtm-scripting#2]
If startup_tools.py is loaded after startup_demo_scripts.py, for example, if I want to load both like this:
![image](https://github.com/qualisys/qtm-scripting/assets/9436418/8ed54a10-d25c-47a2-9a8b-8ae9a037b45a)
I get the following:
![image](https://github.com/qualisys/qtm-scripting/assets/9436418/1ed3900c-ee70-4dcb-be5d-3dd8d47208f9)
The culprit is here:
https://github.com/qualisys/qtm-scripting/blob/113ef154d4d3f1ef03cca46110dd53a1855c9807/startup_tools.py#L13C29-L13C29
```
if this_dir not in sys.path:
    sys.path.append(this_dir)
    sys.path.append(os.path.join(this_dir,"tools"))
    sys.path.append(os.path.join(this_dir,"user"))
```
If startup_demo_scripts.py has been loaded before then this_dir is in sys.path thus "tools" subdir is not added to sys.path and modules cannot be found.

**Comment by ulvs** [comment]
Hi,
Thanks for the feedback, this is addressed in pull request #3
