### ISSUE TITLE
Terminal Window Resize

### ISSUE THREAD

**Issue by ilya112358** [qualisys/qtm-scripting#4]
This is not as much about scripting but about GUI.
![image](https://github.com/qualisys/qtm-scripting/assets/9436418/7c5daf7e-fdc1-4a63-9d11-b9040ee2cbad)
The Terminal window does not resize properly to anything less than 20 lines, part of the window does not fit and becomes unreachable.
![image](https://github.com/qualisys/qtm-scripting/assets/9436418/c17d0710-cfef-4515-a83f-ee74b6a620a9)

**Comment by ulvs** [comment]
Hi,

Thanks for reporting the issue, this will be addressed in the next version of QTM.

Best regards
Martin
