### ISSUE TITLE
Get Analog channels and boards details

### ISSUE THREAD

**Issue by etoshey** [qualisys/qtm-scripting#8]
Hello 

Is there any method to get analog channels' names using the series' Id?

Best regards
Soroosh

**Comment by schoondw** [comment]
Hi,

Unfortunately, it is currently not possible to get the analog channel names. Good point. 

I keep this issue open for now.

Best regards,
Erwin

**Comment by etoshey** [comment]
Great, thanks

**Comment by bahlborn** [comment]
Hello. This feature has been added and is scheduled for release in QTM 2025.1
